/* tslint:disable */
/* eslint-disable */
/**
 * nest-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateMenuDto
 */
export interface CreateMenuDto {
  /**
   * 菜单id
   * @type {number}
   * @memberof CreateMenuDto
   */
  menuId: number
  /**
   * 父菜单id
   * @type {number}
   * @memberof CreateMenuDto
   */
  parentMenuId: number
  /**
   * 菜单名
   * @type {string}
   * @memberof CreateMenuDto
   */
  title: string
  /**
   * URL路径
   * @type {string}
   * @memberof CreateMenuDto
   */
  path: string
  /**
   * 标题
   * @type {string}
   * @memberof CreateMenuDto
   */
  name: string
  /**
   * 组件路径
   * @type {string}
   * @memberof CreateMenuDto
   */
  component: string
  /**
   * 重定向
   * @type {string}
   * @memberof CreateMenuDto
   */
  redirect: string
  /**
   * 图标
   * @type {string}
   * @memberof CreateMenuDto
   */
  icon: string
  /**
   * 是否隐藏
   * @type {boolean}
   * @memberof CreateMenuDto
   */
  hidden: boolean
}
