/* tslint:disable */
/* eslint-disable */
/**
 * nest-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
  /**
   * 用户id
   * @type {number}
   * @memberof CreateUserDto
   */
  id: number
  /**
   * 用户名
   * @type {string}
   * @memberof CreateUserDto
   */
  userName: string
  /**
   * 密码
   * @type {string}
   * @memberof CreateUserDto
   */
  password: string
  /**
   * 邮箱
   * @type {string}
   * @memberof CreateUserDto
   */
  email: string
  /**
   * 角色
   * @type {string}
   * @memberof CreateUserDto
   */
  role: string
  /**
   * 手机号
   * @type {string}
   * @memberof CreateUserDto
   */
  phone: string
  /**
   * 地址
   * @type {string}
   * @memberof CreateUserDto
   */
  address: string
  /**
   * 状态
   * @type {number}
   * @memberof CreateUserDto
   */
  state: number
}
