/* tslint:disable */
/* eslint-disable */
/**
 * nest-admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {
  /**
   * 用户名
   * @type {string}
   * @memberof LoginDto
   */
  userName: string
  /**
   * 邮箱
   * @type {string}
   * @memberof LoginDto
   */
  email: string
  /**
   * 密码
   * @type {string}
   * @memberof LoginDto
   */
  password: string
  /**
   * 验证码
   * @type {string}
   * @memberof LoginDto
   */
  code: string
}
